server.port: 6050


logging:
  level:
    root: info
    com.example.singlemodule: debug


logging.level:
  org.hibernate.SQL: debug

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
    username: sa # username과 password는 자신의 설정에 맞게
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  thymeleaf:
    cache: false


jpa:
  open-in-view: false
  hibernate:
    ddl-auto: create # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    use-new-id-generator-mappings: true
  show-sql: true
  properties:
    hibernate.enable_lazy_load_no_trans: true
    hibernate.format_sql: true




