server.port: 6050

spring.thymeleaf.cache: false


logging:
  level:
    root: info
    com.example.board: debug


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  security:
    user:
      name: msj1234
      password: 0709



jpa:
  open-in-view: false
  hibernate:
    ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    use-new-id-generator-mappings: false
  show-sql: true
  properties:
    hibernate.enable_lazy_load_no_trans: true
    hibernate.format_sql: true




